- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - yarn
    - eslint
    - typescript-language-server
    - typescript
    - ts-node
    - prettier
    - nx
  tags:
    - install
    - node
